### PR TITLE
Merge react-utils into this project

### PR DESCRIPTION
**Pull request by gfx**
As described in #39, and related to #31.

---

(Updated)

Finally I have inlined react-utils' `map()` into the project. It's really easy and coverage safe.

### CODE REVIEW

**Comment by alexcurtis** [comment]
@gfx Very nice. Thanks! I'll get this merged sometime today and published to npm.

**Comment by gfx** [comment]
Thanks! Can't wait! 😆

**Comment by gfx** [comment]
Hi. How's it going?

**Comment by gfx** [comment]
Resolved the conflict.

**Comment by alexcurtis** [comment]
@gfx sorry its taken so long. This has been merged + published to npm. Thanks for your help! 👍

**Comment by gfx** [comment]
No problem. Thank you!

**Pull request merged**
