### PR TITLE
Updated radium

### PR DESCRIPTION
**Pull request by woodyrew**
Addresses #40

### CODE REVIEW

**Comment by woodyrew** [comment]
Already merged

**Comment by woodyrew** [comment]
This hasn't been merged into `master`.

**Comment by woodyrew** [comment]
@alexcurtis Any chance of merging and publishing this fix please?

**Comment by alexcurtis** [comment]
@woodyrew merged + published. Sorry it took so long. Thanks for your effort! :)

**Comment by woodyrew** [comment]
@alexcurtis No problem. It wasn't a revolutionary PR but if it helps out then that's good. Thanks

**Pull request merged**
